package views;

import DataBase.Conexion;
import Models.Pieza;

import java.awt.BorderLayout;
import java.awt.GridLayout;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

public class CheckParts extends JFrame {

    private int idMantenimiento;

    private JPanel panel;

    private ArrayList<Pieza> listaPiezas;
    private ArrayList<JCheckBox> listaChecks;

    public CheckParts(int idMantenimiento) {

        this.idMantenimiento = idMantenimiento;

        setTitle("Seleccionar piezas");
        setSize(400, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        listaPiezas = new ArrayList<>();
        listaChecks = new ArrayList<>();

        panel = new JPanel();
        panel.setLayout(new GridLayout(0, 1));

        JScrollPane scroll = new JScrollPane(panel);

        JButton btnGuardar = new JButton("Guardar");

        btnGuardar.addActionListener(e -> guardarPiezas());

        add(scroll, BorderLayout.CENTER);
        add(btnGuardar, BorderLayout.SOUTH);

        cargarPiezas();
    }

    private void cargarPiezas() {

        Connection cn = null;

        try {

            cn = Conexion.conectar();

            String sql
                    = "SELECT * FROM inventario_piezas";

            PreparedStatement ps = cn.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                Pieza pieza = new Pieza();

                pieza.setIdPieza(rs.getInt("id_pieza"));
                pieza.setNombre(rs.getString("nombre"));

                listaPiezas.add(pieza);

                JCheckBox check = new JCheckBox(
                        pieza.getNombre()
                );

                listaChecks.add(check);

                panel.add(check);
            }

            rs.close();
            ps.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Error: " + e.getMessage()
            );

        } finally {

            Conexion.desconectar(cn);
        }
    }

    private void guardarPiezas() {

        Connection cn = null;

        try {

            cn = Conexion.conectar();

            String sql
                    = "INSERT INTO detalle_mantenimiento "
                    + "(id_mantenimiento, id_pieza, cantidad) "
                    + "VALUES (?, ?, ?)";

            PreparedStatement ps = cn.prepareStatement(sql);

            for (int i = 0; i < listaChecks.size(); i++) {

                if (listaChecks.get(i).isSelected()) {

                    Pieza pieza = listaPiezas.get(i);

                    ps.setInt(1, idMantenimiento);
                    ps.setInt(2, pieza.getIdPieza());
                    ps.setInt(3, 1);

                    ps.executeUpdate();
                }
            }

            JOptionPane.showMessageDialog(
                    null,
                    "Piezas guardadas"
            );

            dispose();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Error: " + e.getMessage()
            );

        } finally {

            Conexion.desconectar(cn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new CheckParts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
