/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import DataBase.Conexion;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridLayout;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author usuario
 */
public class DetailsMain extends JFrame {

    private int idMantenimiento;

    private JLabel lblEquipo;
    private JLabel lblSerie;
    private JLabel lblTecnico;
    private JLabel lblFecha;
    private JLabel lblTipo;
    private JLabel lblEstado;

    private JTextArea txtDescripcion;
    private JTextArea txtObservaciones;
    private JTextArea txtPiezas;

    public DetailsMain(int idMantenimiento) {

        this.idMantenimiento = idMantenimiento;

        initComponents();

        crearInterfaz();

        cargarDetalles();

        cargarPiezas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearInterfaz() {

        setTitle("Detalles del mantenimiento");

        setSize(700, 600);

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        getContentPane().removeAll();

        setLayout(new BorderLayout());

        JPanel panelSuperior = new JPanel();

        panelSuperior.setLayout(new GridLayout(6, 2, 10, 10));

        panelSuperior.setBorder(
                BorderFactory.createTitledBorder("Información")
        );

        lblEquipo = new JLabel();

        lblSerie = new JLabel();

        lblTecnico = new JLabel();

        lblFecha = new JLabel();

        lblTipo = new JLabel();

        lblEstado = new JLabel();

        panelSuperior.add(new JLabel("Equipo:"));
        panelSuperior.add(lblEquipo);

        panelSuperior.add(new JLabel("Número serie:"));
        panelSuperior.add(lblSerie);

        panelSuperior.add(new JLabel("Técnico:"));
        panelSuperior.add(lblTecnico);

        panelSuperior.add(new JLabel("Fecha:"));
        panelSuperior.add(lblFecha);

        panelSuperior.add(new JLabel("Tipo:"));
        panelSuperior.add(lblTipo);

        panelSuperior.add(new JLabel("Estado:"));
        panelSuperior.add(lblEstado);

        JPanel panelCentro = new JPanel();

        panelCentro.setLayout(new GridLayout(3, 1, 10, 10));

        panelCentro.setBorder(
                BorderFactory.createEmptyBorder(10, 10, 10, 10)
        );

        txtDescripcion = new JTextArea();

        txtObservaciones = new JTextArea();

        txtPiezas = new JTextArea();

        txtDescripcion.setLineWrap(true);

        txtObservaciones.setLineWrap(true);

        txtPiezas.setLineWrap(true);

        txtDescripcion.setWrapStyleWord(true);

        txtObservaciones.setWrapStyleWord(true);

        txtPiezas.setWrapStyleWord(true);

        txtDescripcion.setEditable(false);

        txtObservaciones.setEditable(false);

        txtPiezas.setEditable(false);

        txtDescripcion.setFont(
                new Font("Segoe UI", Font.PLAIN, 14)
        );

        txtObservaciones.setFont(
                new Font("Segoe UI", Font.PLAIN, 14)
        );

        txtPiezas.setFont(
                new Font("Segoe UI", Font.PLAIN, 14)
        );

        JPanel panelDesc = new JPanel(new BorderLayout());

        panelDesc.setBorder(
                BorderFactory.createTitledBorder("Descripción")
        );

        panelDesc.add(new JScrollPane(txtDescripcion));

        JPanel panelObs = new JPanel(new BorderLayout());

        panelObs.setBorder(
                BorderFactory.createTitledBorder("Observaciones")
        );

        panelObs.add(new JScrollPane(txtObservaciones));

        JPanel panelPiezas = new JPanel(new BorderLayout());

        panelPiezas.setBorder(
                BorderFactory.createTitledBorder("Piezas utilizadas")
        );

        panelPiezas.add(new JScrollPane(txtPiezas));

        panelCentro.add(panelDesc);

        panelCentro.add(panelObs);

        panelCentro.add(panelPiezas);

        add(panelSuperior, BorderLayout.NORTH);

        add(panelCentro, BorderLayout.CENTER);

        revalidate();

        repaint();
    }

    /**
     * @param args the command line arguments
     */
    private void cargarDetalles() {

        Connection cn = null;

        try {

            cn = Conexion.conectar();

            String sql
                    = "SELECT "
                    + "m.*, "
                    + "e.modelo, "
                    + "e.numero_serie, "
                    + "t.user AS tecnico "
                    + "FROM mantenimientos m "
                    + "INNER JOIN equipos e "
                    + "ON m.id_equipo = e.id_equipo "
                    + "LEFT JOIN tecnicos t "
                    + "ON m.id_tecnico = t.id_tecnico "
                    + "WHERE m.id_mantenimiento = ?";

            PreparedStatement ps = cn.prepareStatement(sql);

            ps.setInt(1, idMantenimiento);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {

                lblEquipo.setText(
                        rs.getString("modelo")
                );

                lblSerie.setText(
                        rs.getString("numero_serie")
                );

                lblTecnico.setText(
                        rs.getString("tecnico")
                );

                lblFecha.setText(
                        rs.getString("fecha")
                );

                lblTipo.setText(
                        rs.getString("tipo")
                );

                lblEstado.setText(
                        rs.getString("estado_equipo")
                );

                txtDescripcion.setText(
                        rs.getString("descripcion")
                );

                txtObservaciones.setText(
                        rs.getString("observaciones")
                );
            }

            rs.close();
            ps.close();

        } catch (Exception e) {

            System.out.println(e.getMessage());

        } finally {

            Conexion.desconectar(cn);
        }
    }

    private void cargarPiezas() {

        Connection cn = null;

        try {

            cn = Conexion.conectar();

            String sql
                    = "SELECT "
                    + "p.nombre, "
                    + "d.cantidad "
                    + "FROM detalle_mantenimiento d "
                    + "INNER JOIN inventario_piezas p "
                    + "ON d.id_pieza = p.id_pieza "
                    + "WHERE d.id_mantenimiento = ?";

            PreparedStatement ps = cn.prepareStatement(sql);

            ps.setInt(1, idMantenimiento);

            ResultSet rs = ps.executeQuery();

            StringBuilder piezas = new StringBuilder();

            while (rs.next()) {

                piezas.append("• ");

                piezas.append(
                        rs.getString("nombre")
                );

                piezas.append(" | Cantidad: ");

                piezas.append(
                        rs.getInt("cantidad")
                );

                piezas.append("\n");
            }

            txtPiezas.setText(
                    piezas.toString()
            );

            rs.close();
            ps.close();

        } catch (Exception e) {

            System.out.println(e.getMessage());

        } finally {

            Conexion.desconectar(cn);
        }
    }

    public static void main(String args[]) {

        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new DetailsMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
